services:
  minio:
    image: minio/minio
    container_name: 3dom-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-adminpass}
    volumes:
      - data-minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5

  init-minio:
      image: minio/mc
      depends_on:
        minio:
          condition: service_healthy
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc alias set dockerminio http://minio:9000 ${MINIO_ROOT_USER:-admin} ${MINIO_ROOT_PASSWORD:-adminpass};
        /usr/bin/mc mb dockerminio/bucket || true;
        exit 0;
        "

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - migrations:/migrations

  admin:
      image: adminer
      restart: always
      depends_on:
        - db
      ports:
        - 8081:8080
volumes:
  data-minio:
  postgres_data:
  migrations: