env: "local"
http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
database: #sql
  name: "db"
  host: "localhost"
  port: "5432"
  username: "admin"
  password: "admin"
  migration_path: "migrations"
filestorage: #MinIO
  address: "localhost:9000"
  username: "admin"
  password: "adminpass"
  bucketname: "bucket"
kafka:
  address: "localhost:9092"
